package com.adamratzman.zwift.models.events

import kotlinx.serialization.Serializable

@Serializable
data class ZwiftEvent(
    val accessExpression: String? = null,
    val auxiliaryUrl: String,
    val bikeHash: Int? = null,
    val cullingType: String,
    val customUrl: String,
    val description: String,
    val distanceInMeters: Double,
    val durationInSeconds: Int,
    val eventSecret: String? = null,
    val eventSeries: ZwiftEventSeries,
    val eventStart: String,
    val eventSubgroups: List<ZwiftEventSubgroup>,
    val eventType: String, // known: GROUP_WORKOUT, RACE, GROUP_RIDE
    val followeeEntrantCount: Int,
    val followeeJoinedCount: Int,
    val followeeSignedUpCount: Int,
    val id: Int,
    val imageS3Bucket: String? = null,
    val imageS3Name: String? = null,
    val imageUrl: String,
    val imported: Boolean,
    val invisibleToNonParticipants: Boolean,
    val jerseyHash: Int? = null,
    val laps: Int,
    val lateJoinInMinutes: Int? = null,
    val mapId: Int,
    // val microserviceEventVisibility: Any,
    // val microserviceExternalResourceId: Any,
    // val microserviceName: String,
    // val minGameVersion: Any,
    val name: String,
    val overrideMapPreferences: Boolean,
    val parentId: Int,
    val privateEvent: Boolean,
    val publishRecurring: Boolean,
    // val qualificationRuleIds: Any,
    val recordable: Boolean,
    val recurring: Boolean,
    val restricted: Boolean,
    val routeId: Long,
    val routeUrl: String? = null,
    val rulesId: Int,
    val rulesSet: List<String>,
    val shortDescription: String,
    val shortName: String,
    val sport: String,
    val tags: List<String>,
    //  val timeTrialOptions: Any,
    val totalEntrantCount: Int,
    val totalJoinedCount: Int,
    val totalSignedUpCount: Int,
    val type: String,
    val unlisted: Boolean,
    val visible: Boolean,
    val workoutHash: Int? = null,
    val worldId: Int
)

@Serializable
data class ZwiftEventSeries(
    val description: String? = null,
    val id: Int,
    val imported: Boolean,
    val name: String
)

@Serializable
data class ZwiftEventSubgroup(
    // val accessValidationResult: Any,
    val auxiliaryUrl: String,
    val bikeHash: Int? = null,
    val customUrl: String,
    val description: String,
    val distanceInMeters: Double,
    val durationInSeconds: Int,
    val eventSubgroupStart: String,
    val fieldLimit: Int? = null,
    val followeeEntrantCount: Int,
    val followeeJoinedCount: Int,
    val followeeSignedUpCount: Int,
    val fromPaceValue: Double,
    val id: Int,
    val invitedLeaders: List<Int>,
    //val invitedSweepers: List<Any>,
    val jerseyHash: Int,
    val label: Int,
    val laps: Int,
    val lateJoinInMinutes: Int? = null,
    val lineUpEnd: String,
    val lineUpStart: String,
    val mapId: Int,
    val name: String,
    val overrideMapPreferences: Boolean,
    val paceType: Int,
    // val qualificationRuleIds: Any,
    val registered: Boolean,
    val registrationEnd: String,
    val registrationStart: String,
    val registrationStatus: Int,
    val routeId: Long,
    val routeUrl: String? = null,
    val rulesId: Int,
    val rulesSet: List<String>,
    val signedUp: Boolean,
    val signupStatus: Int,
    val startLocation: Int,
    val subgroupLabel: String,
    val tags: List<String>,
    // val timeTrialOptions: Any,
    val toPaceValue: Double,
    val totalEntrantCount: Int,
    val totalJoinedCount: Int,
    val totalSignedUpCount: Int,
    val workoutHash: Int? = null
)